mtproxy_replicas: 2
mtproxy_image: "telegrammessenger/proxy:latest"
mtproxy_secret: "00000000000000000000000000000000"
mtproxy_base_port: 10000
haproxy_port: 443
haproxy_stats_port: 8404
haproxy_balance_algorithm: "leastconn"
tproxy_fwmark: "1"
tproxy_route_table: "100"
