---
dependencies: []
galaxy_info:
  author: virton
  description: HAProxy TCP load balancer with TPROXY transparent mode
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
