---
- name: Apply sysctl
  ansible.builtin.command: sysctl --system
  changed_when: false

- name: Reload systemd daemon for tproxy
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart tproxy service
  ansible.builtin.systemd:
    name: tproxy
    state: restarted
