---
- name: Apply sysctl
  command: sysctl --system
  changed_when: false

- name: Reload systemd daemon
  systemd:
    daemon_reload: true

- name: Restart tproxy service
  systemd:
    name: tproxy
    state: restarted
