---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
      - python3-docker
      - iptables-persistent
      - haproxy
      - socat
      - qemu-user-static
      - binfmt-support
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Enable Docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Add ansible user to docker and haproxy groups
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups:
      - docker
      - haproxy
    append: true
